texasfuelratepredictor/fuel/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField, DateField, SubmitField, IntegerField
from wtforms.validators import DataRequired

class FuelForm(FlaskForm):
      gallon = IntegerField('# of Gallons', validators=[DataRequired()])
      address = StringField('Address')
      d_deliver = DateField('Delivery Date', validators=[DataRequired()])
      suggestp = DecimalField('Suggested Price')
      totalp = DecimalField('Total Price')
      submit = SubmitField('Calculate Fuel Rate')

texasfuelratepredictor/fuel/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, login_required
from texasfuelratepredictor import db
from texasfuelratepredictor.models import User, ClientInformation, Quote
from texasfuelratepredictor.fuel.forms import FuelForm
import datetime

fuel = Blueprint('fuel', __name__)

#to create a new fuel rate quote
@fuel.route("/fuel_rate_price",  methods=['GET', 'POST'])
@login_required
def fuel_rate_cal():
    form = FuelForm()
    client_info = ClientInformation.query.filter_by(client=current_user.email).first()
    clientHistory = Quote.query.filter_by(client_em=current_user.email)
    count = clientHistory.count()#
    if form.validate_on_submit():
        newFuel = Quote(gallon=form.gallon.data, 
                         address=form.address.data, 
                         datedelivery=form.d_deliver.data, 
                         suggested_price=float(form.suggestp.data), # will try to fix in html later
                         total_price =float(form.totalp.data),      # will try to fix in html later
                         client_em=current_user.email)
        db.session.add(newFuel)
        db.session.commit()
        flash('New Fuel Rate Quote in History', 'success')
        return redirect(url_for('fuel.history'))
    return render_template('fuel_form.html', title='Fuel Quote Form',
                form = form, legend='Fuel Rate Quote', client= client_info,
                clientHistory=count)


#to check fuel quote history
@fuel.route("/fuel_history",  methods=['GET', 'POST'])
@login_required
def history():
    email = current_user.email
    user = ClientInformation.query.filter_by(client=email).first_or_404()
    page = request.args.get('page', 1, type=int)
    clientHistory = Quote.query.filter_by(client_em=email)\
                 .order_by(Quote.id.desc())\
                 .paginate(per_page=3, page=page)

    return render_template('fuel_history.html', title='Fuel Quote History',
                legend='Fuel Quote History', listQuote= clientHistory, user=user)

#to see a past fuel quote
@fuel.route("/fuel_history/<int:quote_id>",  methods=['GET', 'POST'])
@login_required
def pastQuote(quote_id):
    quote = Quote.query.get_or_404(quote_id)
    user = ClientInformation.query.filter_by(client=current_user.email).first_or_404()
    return render_template('past_quote.html', title='Past Fuel Quote', quote=quote, user=user)

  
#delete a past quote
@fuel.route("/fuel_history/<int:quote_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_quote(quote_id):
    quote = Quote.query.get_or_404(quote_id)
    db.session.delete(quote)
    db.session.commit()
    flash('A past quote has been erased!', 'success')
    return redirect(url_for('fuel.history'))

texasfuelratepredictor/main/routes.py
from flask import render_template, request, Blueprint

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    return render_template('home.html')


@main.route("/about")
def about():
    return render_template('about.html', title='About')

texasfuelratepredictor/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from texasfuelratepredictor import db, bcrypt
from texasfuelratepredictor.models import User, ClientInformation
from texasfuelratepredictor.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                           RequestResetForm, ResetPasswordForm)
from texasfuelratepredictor.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.about'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.about'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    client_info = ClientInformation(fullname=form.fullname.data,
            address1=form.address1.data,
            address2=form.address2.data,
            city=form.city.data,
            state=form.state.data,
            zipcode=form.zipcode.data,
            client=current_user.email)
    db.session.add(client_info)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file) #

    if form.validate_on_submit():
        client_info = ClientInformation.query.filter_by(client=current_user.email).first()#fix the issue of wrong update
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        client_info.fullname = form.fullname.data
        client_info.address1 = form.address1.data
        client_info.address2 = form.address2.data
        client_info.city = form.city.data
        client_info.state = form.state.data
        client_info.zipcode = form.zipcode.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
       # return redirect(url_for('users.account'))
        return render_template('account.html', title='Account',
            image_file=image_file, form=form, client=client_info)

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.fullname.data = client_info.fullname
        form.address1.data = client_info.address1
        form.address2.data = client_info.address2
        form.city.data = client_info.city
        form.state.data = client_info.state
        form.zipcode.data = client_info.zipcode

    return render_template('account.html', title='Account',
            image_file=image_file, form=form, client=client_info)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password. Please check your email.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid token or token expired', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password Updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

texasfuelratepredictor/templates/about.html
<!-- template inheritence -->
{% extends "layout.html" %}
{% block content %}
    <div style="background-color: rgb(210, 255, 47); width: 400px">
            <h2 style="text-align: center">  About TFRP </h2>
    </div>
    <h2> Welcome to Texas Fuel Rate Predictor! </h2>

    <p>We work with the company to provide firm software for our client's needs.</p>
    <p>TFRP predicts the fuel rate based on the:</p>
    <ol>
        <li>Client's Location</li>
        <li>Competitor's Rate</li>
        <li>Client's Rate History</li>
        <li>Gallons Requested</li>
        <li>Company's profit margin</li>
        <li>Seasonal rate fluctuation</li>
    </ol>


    <p>To start first login in or <a href="{{ url_for('users.register') }}">create an account</a></p>
    <p>If you're already logged in <a href="{{ url_for('users.account') }}">update your account </a>and enter the required information</p>
    <p>If you already updated your account go ahead and <a href="{{ url_for('fuel.fuel_rate_cal') }}">calculate your first fuel quote!</a></p>

{% endblock content %}

texasfuelratepredictor/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <!-- FORM HERE -->
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border_bottom mb-4">Account Info</legend>

                <!-- username -->
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span> 
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <!-- email -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span> {{ error }} </span> 
                        {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <!-- picture -->
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger"> {{ error }} </span> 
                        {% endfor %}
                    {% endif %}
                </div>

                <!-- fullname -->
                <div class="form-group">
                    {{ form.fullname.label(class="form-control-label") }}
                    {% if form.fullname.errors %}
                        {{ form.fullname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                        {% for error in form.fullname.errors %}
                            <span>{{ error }}</span> 
                        {% endfor %}
                        </div>
                    {% else %}

                        {% set fullname_string = [client.fullname] %}
                        {{ form.fullname(class="form-control form-control-lg",
                                         value=fullname_string, style="background-color:transparent",
                                         id="fullname") }}

                    {% endif %}
                </div>

                <!-- address1 -->
                <div class="form-group">
                    {{ form.address1.label(class="form-control-label") }}
                    {% if form.address1.errors %}
                        {{ form.address1(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                        {% for error in form.address1.errors %}
                            <span>{{ error }}</span> 
                        {% endfor %}
                        </div>
                    {% else %}
                        {% set address1_string = [client.address1] %}
                        {{ form.address1(class="form-control form-control-lg",
                                         value=address1_string, style="background-color:transparent",
                                         id="address1") }}
                    {% endif %}
                </div>

                <!-- address2 -->
                <div class="form-group">
                    {{ form.address2.label(class="form-control-label") }}
                    {% if form.address2.errors %}
                        {{ form.address2(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                        {% for error in form.address2.errors %}
                            <span>{{ error }}</span> 
                        {% endfor %}
                        </div>
                    {% else %}
                        {% set address2_string = [client.address2] %}
                        {{ form.address2(class="form-control form-control-lg",
                                         value=address2_string, style="background-color:transparent",
                                         id="address2") }}
                    {% endif %}
                </div>

                <!-- city -->
                <div class="form-group">
                    {{ form.city.label(class="form-control-label") }}
                    {% if form.city.errors %}
                    {{ form.city(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.city.errors %}
                        <span>{{ error }}</span> 
                        {% endfor %}
                    </div>
                    {% else %}
                        {% set city_string = [client.city] %}
                        {{ form.city(class="form-control form-control-lg",
                                         value=city_string, style="background-color:transparent",
                                         id="city") }}
                    {% endif %}
                </div>

                <!-- state -->
                <div class="form-group">
                    {{ form.state.label(class="form-control-label") }}
                    {% if form.state.errors %}
                    {{ form.state(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.state.errors %}
                        <span>{{ error }}</span> 
                        {% endfor %}
                    </div>
                    {% else %}
                        {% set state_string = [client.state] %}
                        {{ form.state(class="form-control form-control-lg",
                                         value=state_string, style="background-color:transparent",
                                         id="state") }}
                    {% endif %}
                </div>

                <!-- zipcode -->
                <div class="form-group">
                    {{ form.zipcode.label(class="form-control-label") }}
                    {% if form.zipcode.errors %}
                    {{ form.zipcode(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.zipcode.errors %}
                        <span>{{ error }}</span> 
                        {% endfor %}
                    </div>
                    {% else %}
                        {% set zipcode_string = [client.zipcode] %}
                        {{ form.zipcode(class="form-control form-control-lg",
                                         value=zipcode_string, style="background-color:transparent",
                                         id="zipcode") }}
                    {% endif %}
                </div>
            </fieldset>

            <!-- submit -->
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>                                                                 
{% endblock content %}

texasfuelratepredictor/templates/fuel_history.html
{% extends "layout.html" %}
{% block content %}
<h3 class="mb-3"> Fuel Quote History for {{ user.fullname }} ({{ listQuote.total}})</h3>>
    {% if listQuote %}
        {% for quote in listQuote.items %}
            <article class = "media content-section">
                <div class="col-md-4">
                    <h5>Time created: <a class="article-title" 
                                      href="{{ url_for('fuel.pastQuote',quote_id=quote.id)}}">
                                      {{quote.datepost.strftime('%Y-%m-%d')}}
                                      </a></h5>
                </div>
                <div class="col-md-8">
                    <ul>
                        <li>Gallon:            {{quote.gallon}}</li>
                        <li>Address:           {{quote.address}}</li>
                        <li>Date delivery:     {{quote.datedelivery}}</li>
                        <li>Suggested price: $ {{ "$%.2f"|format(quote.suggested_price)}}</li> 
                        <li>Total price:     $ {{"$%.2f"|format(quote.total_price)}}</li>
                      </ul>
                </div>
            </article>      
        {% endfor%}
        {% for page_num in listQuote.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if page_num %}
             {% if listQuote.page == page_num %}
                 <a class="btn btn-info mb-4" href="{{ url_for('fuel.history', page=page_num) }}">{{ page_num }} </a>
             {% else %}
                 <a class="btn btn-outline-info mb-4" href="{{ url_for('fuel.history', page=page_num) }}">{{ page_num }} </a>
             {% endif %} 
          {% else%}
          {% endif %}
        {% endfor %}
    {% endif %}
     
{% endblock content %}

texasfuelratepredictor/templates/home.html
<!-- template inheritence -->
{% extends "layout.html" %}
{% block content %}
<div style="background-color: transparent; height: 300px; border: 1px">
    <div style="border-color: blue;">
        <h2> WELCOME TO TEXAS FUEL RATE PREDICTOR!</h2>
    </div>
    
    <div valign="bottom">
        <p>Please <a href="{{ url_for('users.account') }}">update your account information </a> to access or create a fuel quote.</p>
        <p>If you have already updated your account go ahead and <a href="{{ url_for('fuel.fuel_rate_cal') }}">calculate your first fuel quote!</a></p>
    </div>
    
</div>
   
{% endblock content %}

texasfuelratepredictor/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- copied from https://tinyurl.com/y2q9ucgz -->
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 

        <!-- added for style using flask function url_for to find static directory -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        <!-- added CSS link for icons-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        {% if title %}
        <title>TexasFuelRatePredictor App - {{ title }}</title>
        {% else %}
        <title>TFRP </title>
        {% endif %}
        <!-- other css file-->
        <link rel="stylesheet" type="text/css" href="layout.css">
    </head>
    <body style="background-image: url('https://images8.alphacoders.com/423/423311.jpg')">
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="opacity: 0.8; ">
                <div class="container">
                    <i class="material-icons" style="font-size:30px;color:red">local_gas_station</i>
                    <a class="navbar-brand mr-4" href="/">TFRP</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            {% if current_user.is_authenticated %}
                                
                                <a id="select1" class="nav-item nav-link" href="{{ url_for('fuel.history') }}" >History</a>
                                <a id="select1" class="nav-item nav-link" href="{{ url_for('fuel.fuel_rate_cal') }}">Predictor</a>
                                <a id="select1" class="nav-item nav-link" href="{{ url_for('users.account') }}" >Account </a>
                                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}" >Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('users.register') }}" >Register</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.login') }}" >Login</a>
                                <i style='font-size:15px' class='fas'>&#xf3c1;</i>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
     
        <main role="main" class="container" style="position: relative; min-height: 85vh;">
        <div class="row" style="padding-bottom: 2.5rem">
            <div class="col-md-8 hidden-xs" style="background-color: whitesmoke">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4 hidden-xs" style="background-color: transparent; ">
                    <h1 class="heading" style="color:white; opacity: 0.5; font-size: 48px;  text-align: center;"> Texas Fuel Rate Predictor </h1>
            </div>
        </div>
        <!--footer-->

        </main>
        <div class="footer navbar-fixed-bottom" 
             style="color: white; height: 2.5rem; width: 100%; position: absolute;  background-image: url(http://style24x7.com/wp-content/uploads/2018/12/Background-Wallpaper-HD-Autumn-Nature-Photo-120.jpg)">
            <p style="text-align: center">© 2019 Texas Fuel Rate Predictor</p>
       </div>
        <!--

    -->

        <!-- copied from https://tinyurl.com/y2q9ucgz -->
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

texasfuelratepredictor/templates/login.html
<!-- Login Page -->
<!-- template inheritence -->
<!-- using jinja2 syntax -->
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border_bottom mb-4" style="height: 50px; padding: 0;  background-image: url(http://style24x7.com/wp-content/uploads/2018/12/Background-Wallpaper-HD-Autumn-Nature-Photo-120.jpg);">
                   <h3 style="color: white; text-align: center"> Log In </h3>
                </legend>

                <!-- email -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span> 
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <!-- password -->
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span> 
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
            </fieldset>

            <!-- submit -->
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
            </small>
            </div>


        </form>
    </div>
    <div class="border-top pt-3"> 
        <small class="text-muted">
            Don't have an account?<a class="ml-2" href="{{ url_for('users.register') }}">Sign up</a>
        </small>
    </div>
{% endblock content %}

texasfuelratepredictor/templates/past_quote.html
{% extends "layout.html" %}
{% block content %}
    <article class = "media content-section">
        <div class ="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">Client: {{user.fullname}} </a>
           
                    <div>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal"> Delete </button>
                    </div>
              
            </div>
            <ul>
                <li>Gallon:            {{quote.gallon}}</li>
                <li>Address:           {{quote.address}}</li>
                <li>Date delivery:     {{quote.datedelivery}}</li>
                <li>Suggested price: $ {{quote.suggested_price}}</li> 
                <li>Total price:     $ {{quote.total_price}}</li>
            </ul>            
        </div>

    </article> 
     <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Do you want to Delete this record?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('fuel.delete_quote', quote_id=quote.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>     

{% endblock content %}